---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[hygieia-liatrio::default]
      - recipe[hygieia-liatrio::mongodb]
      - recipe[hygieia-liatrio::node]
      - recipe[hygieia-liatrio::apache2]
    attributes: {
      java.jdk_version: "8",
      foo: "bar"
    }
